// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID         int32            `json:"id"`
	Uuid       string           `json:"uuid"`
	PrID       pgtype.Int4      `json:"pr_id"`
	Sha        string           `json:"sha"`
	ApprovedOn pgtype.Timestamp `json:"approved_on"`
}

type GhUser struct {
	ID    int32  `json:"id"`
	Login string `json:"login"`
}

type PullRequest struct {
	ID       int32       `json:"id"`
	RepoID   pgtype.Int4 `json:"repo_id"`
	PrID     int32       `json:"pr_id"`
	PrNumber int32       `json:"pr_number"`
	OpenedBy pgtype.Int4 `json:"opened_by"`
	IsMerged pgtype.Bool `json:"is_merged"`
}

type PullRequestAction struct {
	Name string `json:"name"`
}

type PullRequestEvent struct {
	ID          int32            `json:"id"`
	PrID        pgtype.Int4      `json:"pr_id"`
	Action      pgtype.Text      `json:"action"`
	Sha         pgtype.Text      `json:"sha"`
	IsMerged    pgtype.Bool      `json:"is_merged"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type Repo struct {
	ID   int32  `json:"id"`
	Org  string `json:"org"`
	Name string `json:"name"`
}
