
# Group Api

## /approval

### POST [POST]


+ Request (application/json)



    + Body

            {
                "uuid": "e5028855-f908-4f88-8037-44ff2c6dfc1a",
                "is_approved": true
            }        

+ Response 201 (application/json)



    + Body

            {
                "uuid": "e5028855-f908-4f88-8037-44ff2c6dfc1a",
                "is_approved": true
            }        



## /approval/{id}

+ Parameters
    + id: `4bf55d6b-b68e-47a3-b272-5fa4a6af0251` (string)

### GET [GET]


+ Response 200 (application/json)



    + Body

            {
                "id": 1,
                "uuid": "4bf55d6b-b68e-47a3-b272-5fa4a6af0251",
                "pr_id": 555,
                "sha": "038d718da6a1ebbc6a7780a96ed75a70cc2ad6e2",
                "is_approved": false,
                "last_updated": "0001-01-01T00:00:00Z"
            }        



## /approval{?id}

+ Parameters
    + id: `4bf55d6b-b68e-47a3-b272-5fa4a6af0251` (string)

### GET [GET]


+ Response 200 (application/json)



    + Body

            {
                "id": 1,
                "uuid": "4bf55d6b-b68e-47a3-b272-5fa4a6af0251",
                "pr_id": 555,
                "sha": "038d718da6a1ebbc6a7780a96ed75a70cc2ad6e2",
                "is_approved": false,
                "last_updated": "0001-01-01T00:00:00Z"
            }        



## /pull_requests

### GET [GET]


+ Response 200 (application/json)



    + Body

            [
                {
                    "id": 1,
                    "repo_id": 444,
                    "pr_id": 991,
                    "pr_number": 1,
                    "opened_by": 651,
                    "is_merged": false
                }
            ]        



## /webhook_events

### POST [POST]


+ Request (application/json)



    + Body

            {}        

+ Response 200 

