
# Group Api

## /approval

### POST [POST]


+ Request (application/x-www-form-urlencoded)



    + Body

            is_approved=true&uuid=5fcae4d5-fbb6-417d-8267-70f9b0f6d28f        

+ Response 201 (application/json)



    + Body

            {
                "uuid": "5fcae4d5-fbb6-417d-8267-70f9b0f6d28f",
                "is_approved": true
            }        



+ Request (application/json)



    + Body

            {
                "uuid": "5fcae4d5-fbb6-417d-8267-70f9b0f6d28f",
                "is_approved": true
            }        

+ Response 201 (application/json)



    + Body

            {
                "uuid": "5fcae4d5-fbb6-417d-8267-70f9b0f6d28f",
                "is_approved": true
            }        



## /approval/{id}

+ Parameters
    + id: `01482f1e-805b-4b64-a408-3ce3bcf079cd` (string)

### GET [GET]


+ Response 200 (text/html)



    + Body

            
<!DOCTYPE html>
<html>
    <head>
    <title>PR Compliance App</title>    
		
    </head>
    <body>
		<p>The following form must be submitted before the PR can be merged</p>
		<br>
		<h1>Approval</h1>
		<form action="http://localhost:8080/approval" method="POST" novalidate>
			<input type="hidden" id="uuid" name="uuid" value="01482f1e-805b-4b64-a408-3ce3bcf079cd">
			<input type="hidden" id="is_approved" name="is_approved" value="true">	
				<input type="submit" value="Approve">
			</div>
		</form>
    </body>
</html>
	        



## /approval{?id}

+ Parameters
    + id: `01482f1e-805b-4b64-a408-3ce3bcf079cd` (string)

### GET [GET]


+ Response 200 (text/html)



    + Body

            
<!DOCTYPE html>
<html>
    <head>
    <title>PR Compliance App</title>    
		
    </head>
    <body>
		<p>The following form must be submitted before the PR can be merged</p>
		<br>
		<h1>Approval</h1>
		<form action="http://localhost:8080/approval" method="POST" novalidate>
			<input type="hidden" id="uuid" name="uuid" value="01482f1e-805b-4b64-a408-3ce3bcf079cd">
			<input type="hidden" id="is_approved" name="is_approved" value="true">	
				<input type="submit" value="Approve">
			</div>
		</form>
    </body>
</html>
	        



## /health

### GET [GET]


+ Response 200 (application/json)



    + Body

            {
                "alive": true
            }        



## /webhook_events

### POST [POST]


+ Request (application/json)



    + Body

            {}        

+ Response 200 

