name: PR workflow
on: pull_request
jobs:
  go-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run make test
        run: make test

  build-with-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.8.11
      - name: Build with pack (standard)
        run: |
          pack build pr-compliance-app:test \
            --builder paketobuildpacks/ubuntu-noble-builder:latest \
            --trust-builder
